name: HyperConomy
main: regalowl.hyperconomy.bukkit.BukkitConnector
version: 0.976.0
author: RegalOwl
api-version: 1.13
website: http://dev.bukkit.org/server-mods/hyperconomy/
softdepend: [HeroStronghold, Buycraft, Essentials, Vault]
loadbefore: []
commands:
   buy:
      description: Buys items.
      permission: hyperconomy.buy
      permission-message: You don't have permission to do this.
      aliases: [by]
   sell:
      description: Sells items.
      permission: hyperconomy.sell
      permission-message: You don't have permission to do this.
      aliases: [sl]
   value:
      description: Gets information about an item's value.
      permission: hyperconomy.value
      permission-message: You don't have permission to do this.
      aliases: [vl]
   heldvalue:
      description: Gets information about the value of the item you're holding.
      permission: hyperconomy.value
      permission-message: You don't have permission to do this.
      aliases: [hv]
   heldsell:
      description: Sells an amount of the item you're holding.
      permission: hyperconomy.sell
      permission-message: You don't have permission to do this.
      aliases: [hs]
   heldbuy:
      description: Buys an amount of the item you're holding.
      permission: hyperconomy.buy
      permission-message: You don't have permission to do this.
      aliases: [hb]
   xpinfo:
      description: Displays information about experience.
      permission: hyperconomy.info
      permission-message: You do not have permission.
      aliases: [xpi]
   sellall:
      description: Sells all of the items in your inventory.
      permission: hyperconomy.sellall
      permission-message: You don't have permission to do this.
   iteminfo:
      description: Displays information about the item you're holding.
      permission: hyperconomy.info
      permission-message: You don't have permission to do this.
      aliases: [ii]
   topitems:
      description: Lists the items with the most stock
      permission: hyperconomy.top
      permission-message: You don't have permission to do this.
      aliases: [ti]
   lowstock:
      description: Lists the items with the least stock.
      permission: hyperconomy.top
      permission-message: You don't have permission to do this.
      aliases: [low]
   topenchants:
      description: Lists the enchantments with the most stock
      permission: hyperconomy.top
      permission-message: You don't have permission to do this.
      aliases: [te]
   browseshop:
      description: Displays items in the global shop or the specified shop.
      permission: hyperconomy.top
      permission-message: You don't have permission to do this.
      aliases: [bs]
   servershop:
      description: Manages server shops.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [ss]
   settax:
      description: Sets the sales tax for normal purchases.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [stax]
   objectsettings:
      description: Displays the current shop settings for the object you're holding or the one you specify. Also works as /os
      permission: hyperconomy.settings
      permission-message: You do not have permission.
      aliases: [os, ens]
   taxsettings:
      description: Displays the current tax values.
      permission: hyperconomy.settings
      permission-message: You do not have permission.
      aliases: [tsettings, ts]
   hc:
      description: Displays economy help.
      permission: hyperconomy.use
      permission-message: You don't have permission to do this.
   lockshop:
      description: Locks down the shop and most commands.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [ls]
   intervals:
      description: Displays secondary thread repeat intervals.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [ints]
   scalebypercent:
      description: Scales the selected value the the given percent.
      permission: hyperconomy.scalebypercent
      permission-message: You do not have permission.
   notify:
      description: Toggles the chosen item or enchantments notifications.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [not]
   seteconomy:
      description: Sets your economy to the specified one.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [se]
   hceconomy:
      description: Manages economies.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [he]
   economyinfo:
      description: Tells you what economy you are a part of.
      permission: hyperconomy.use
      permission-message: You do not have permission.
      aliases: [ei]
   hcdata:
      description: Exports data from HyperConomy.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   additem:
      description: Adds the item you're holding to the database.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [ai]
   listcategories:
      description: Lists all categories.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [lcat]
   hyperlog:
      description: Displays HyperConomy log information.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [hl]
   makedisplay:
      description: Makes an item display.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [mkd]
   removedisplay:
      description: Removes an item display.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [rdis]
   setlanguage:
      description: Switches language files.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [sela]
   repairsigns:
      description: Repairs InfoSigns within the given radii.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   hcbalance:
      description: Displays player balances.
      permission: hyperconomy.use
      permission-message: You do not have permission.
      aliases: [hcb]
   hctop:
      description: Displays the top player balances.
      permission: hyperconomy.topbalance
      permission-message: You do not have permission.
      aliases: [hct]
   hcpay:
      description: Pays the specified account the specified amount.
      permission: hyperconomy.pay
      permission-message: You do not have permission.
      aliases: [hcp]
   hcgive:
      description: Gives the specified player the specified amount of the specified type.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [hcg]
   toggleeconomy:
      description: Switches between an external economy plugin and the internal HyperConomy economy plugin.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   makeaccount:
      description: Creates a new economy account.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   importbalance:
      description: Imports player account data from other economy plugins.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   audit:
      description: Check to see if an account's balance is what it should be.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   setpassword:
      description: Sets your account password.
      permission: hyperconomy.use
      permission-message: You do not have permission.
   manageshop:
      description: Manages player shops.
      permission: hyperconomy.playershop
      permission-message: You do not have permission.
      aliases: [ms]
   hcset:
      description: Sets various settings within HyperConomy.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [hcs]
   hcdelete:
      description: Deletes objects and accounts within HyperConomy.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [hcd]
   hctest:
      description: Runs plugin tests.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   frameshop:
      description: Creates frame shops.
      permission: hyperconomy.frameshop
      permission-message: You do not have permission.
      aliases: [fs]
   hcbank:
      description: Manages banks.
      permission: hyperconomy.bank
      permission-message: You do not have permission.
      aliases: [bank]      
   hcweb:
      description: Manages the web page.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
   timeeffect:
      description: Adds and removes TimeEffects from HyperConomy.
      permission: hyperconomy.admin
      permission-message: You do not have permission.
      aliases: [hcte]
   hcchestshop:
      description: Manages chest shops.
      permission: hyperconomy.chestshop
      permission-message: You do not have permission.
      aliases: [hccs]
permissions:
    hyperconomy.*:
        description: Gives access to all HyperConomy commands.
        default: op
        children:
            hyperconomy.use: true
            hyperconomy.settings: true
            hyperconomy.admin: true
            hyperconomy.scalebypercent: true
            hyperconomy.createsign: true
            hyperconomy.notify: true
            hyperconomy.shop: true
            hyperconomy.balanceall: true
            hyperconomy.topbalance: true
            hyperconomy.playershop: true
            hyperconomy.playershop.create: true
            hyperconomy.frameshop: true
            hyperconomy.bank: true
            hyperconomy.viewbanks: true
            hyperconomy.taxexempt: true
    hyperconomy.use:
        description: Allows general use of HyperConomy.
        default: true
        children:
            hyperconomy.buy: true
            hyperconomy.sell: true
            hyperconomy.value: true
            hyperconomy.sellall: true
            hyperconomy.info: true
            hyperconomy.top: true
            hyperconomy.xp: true
            hyperconomy.chestshop: true
            hyperconomy.playershop: true
            hyperconomy.playershop.create: true
            hyperconomy.buysign: true
            hyperconomy.sellsign: true
            hyperconomy.pay: true
    hyperconomy.econ:
        description: Allows use of all basic economy commands.
        default: op
        children:
            hyperconomy.balanceall: true
            hyperconomy.pay: true
            hyperconomy.topbalance: true
    hyperconomy.admin:
        description: Allows use of shop management commands.
        default: false
    hyperconomy.buy:
        description: Allows use of buy commands.
        default: false
    hyperconomy.sell:
        description: Allows use of sell commands.
        default: false
    hyperconomy.value:
        description: Allows use of value commands.
        default: false
    hyperconomy.sellall:
        description: Allows use of the sellall command.
        default: false
    hyperconomy.info:
        description: Allows use of item information lookups.
        default: false
    hyperconomy.top:
        description: Allows use of the topitems and topenchants commands.
        default: false
    hyperconomy.settings:
        description: Allows checking the settings.
        default: false
    hyperconomy.error:
        description: Displays error messages if plugin errors occur.
        default: false
    hyperconomy.scalebypercent:
        description: Allows the use of scalebypercent.
        default: false
    hyperconomy.createsign:
        description: Allows the creation of information signs and transaction signs.
        default: false
    hyperconomy.notify:
        description: Sends price/stock notifications.
        default: false
    hyperconomy.xp:
        description: Allows experience trading.
        default: false
    hyperconomy.chestshop:
        description: Allows the creation of chest shops.
        default: false
    hyperconomy.shop:
        description: Allows access to all functions at all shops.
        default: false
    hyperconomy.buysign:
        description: Allows purchasing from transaction signs.
        default: false
    hyperconomy.sellsign:
        description: Allows selling to transaction signs.
        default: false
    hyperconomy.balanceall:
        description: Allows other players' balances to be displayed.
        default: false
    hyperconomy.topbalance:
        description: Allows display of top server balances.
        default: false
    hyperconomy.pay:
        description: Allows sending payment to other players.
        default: false
    hyperconomy.playershop:
        description: Allows the use of the /manageshop command.
        default: false
    hyperconomy.playershop.create:
        description: Allows only the creation of player shops with /ms create.
        default: false
    hyperconomy.frameshop:
        description: Allows the use of the /frameshop command.
        default: false
    hyperconomy.bank:
        description: Allows the use of the /hcbank command.
        default: false
    hyperconomy.viewbanks:
        description: Allows players to view all information about all banks.
        default: false
    hyperconomy.taxexempt:
        description: Allows players to avoid paying taxes in stores
        default: false
